### ISSUE TITLE
failed to create map

### ISSUE THREAD

**Issue by SuconChu** [hyfan1116/pgm_map_creator#1]
failed to create map

I do it following you, could you please help me,
The following is message in terminal:
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    request_publisher (pgm_map_creator/request_publisher)

auto-starting new master
process[master]: started with pid [8592]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ef07e266-5516-11e9-9b16-54e1ade6002e
process[rosout-1]: started with pid [8607]
started core service [/rosout]
process[request_publisher-2]: started with pid [8617]
[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: vector2d.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1018] CHECK failed: generated_database_->Add(encoded_file_descr
iptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
[request_publisher-2] process has died [pid 8617, exit code -6, cmd /home/z/catkin_ws/devel/lib/pgm_map_creator/
request_publisher (-15,15)(15,15)(15,-15)(-15,-15) 5 0.01 /home/z/catkin_ws/src/pgm_map_creator-master/maps/map
__name:=request_publisher __log:=/home/z/.ros/log/ef07e266-5516-11e9-9b16-54e1ade6002e/request_publisher-2.log].
log file: /home/z/.ros/log/ef07e266-5516-11e9-9b16-54e1ade6002e/request_publisher-2*.log
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

THANKYOU！

**Comment by NovoG93** [comment]
I was facing the same problem.
ROS Kinetic + Ubuntu 16.04

Solved the problem based on this link: http://answers.gazebosim.org/question/8928/protobuf-error-for-custom-messages-transport-tutorial/

1) build using msgs/CMakeLists.txt containing:
```
set (msgs
  collision_map_request.proto
  ${PROTOBUF_IMPORT_DIRS}/vector2d.proto
  ${PROTOBUF_IMPORT_DIRS}/header.proto
  ${PROTOBUF_IMPORT_DIRS}/time.proto
)
```
2) change msgs/CMakeLists.txt to: 
```
set (msgs
  collision_map_request.proto
  # ${PROTOBUF_IMPORT_DIRS}/vector2d.proto
  # ${PROTOBUF_IMPORT_DIRS}/header.proto
  # ${PROTOBUF_IMPORT_DIRS}/time.proto
)
```
3) gzserver /path/to/world with `<plugin filename="libcollision_map_creator.so" name="collision_map_creator"/>`
4) Start launchfile
`roslaunch pgm_map_creator request_publisher.launch`

**Comment by fantauzzi** [comment]
Having the same issue with Melodic and Ubuntu 18.04. After implementing the fix above for  msgs/CMakeLists.txt, I cannot build the package anymore, as I get 

```
In file included from /home/fanta/workspace/where_am_I/build/pgm_map_creator/msgs/collision_map_request.pb.cc:5:0:
/home/fanta/workspace/where_am_I/build/pgm_map_creator/msgs/collision_map_request.pb.h:30:10: fatal error: vector2d.pb.h: No such file or directory

```

**Comment by ValerioMagnago** [comment]
@fantauzzi I got the same problem and adding  _target_include_directories_ to the _CMakeLists.txt_ solved the problem.

Below is the  complete _CMakeLists.txt_ that I used: 
```
find_package(Protobuf REQUIRED)

set(PROTOBUF_IMPORT_DIRS)
foreach(ITR ${GAZEBO_INCLUDE_DIRS})
  if(ITR MATCHES ".*gazebo-[0-9.]+$")
    set(PROTOBUF_IMPORT_DIRS "${ITR}/gazebo/msgs/proto")
  endif()
endforeach()

set (msgs
  collision_map_request.proto
  #${PROTOBUF_IMPORT_DIRS}/vector2d.proto
  #${PROTOBUF_IMPORT_DIRS}/header.proto
  #${PROTOBUF_IMPORT_DIRS}/time.proto
)

PROTOBUF_GENERATE_CPP(PROTO_SRCS PROTO_HDRS ${msgs})
add_library(collision_map_creator_msgs SHARED ${PROTO_SRCS})
target_include_directories(collision_map_creator_msgs PUBLIC ${PROTOBUF_INCLUDE_DIRS})
target_link_libraries(collision_map_creator_msgs ${PROTOBUF_LIBRARY})
```

**Comment by sohinimallick16** [comment]
> Having the same issue with Melodic and Ubuntu 18.04. After implementing the fix above for msgs/CMakeLists.txt, I cannot build the package anymore, as I get
> 
> ```
> In file included from /home/fanta/workspace/where_am_I/build/pgm_map_creator/msgs/collision_map_request.pb.cc:5:0:
> /home/fanta/workspace/where_am_I/build/pgm_map_creator/msgs/collision_map_request.pb.h:30:10: fatal error: vector2d.pb.h: No such file or directory
> ```

Hey...I am doing the same course right now. Did you find a solution to this?

**Comment by hyfan1116** [comment]
@sohinimallick16 I updated the repo for Noetic which includes fix to the issues. I am not sure if Udacity's fork fixed this though.
