### ISSUE TITLE
Produced map is rotated by 90 degrees

### ISSUE THREAD

**Issue by david-wb** [hyfan1116/pgm_map_creator#8]
I used this tool to generate a map of a simple world, but the resulting map was rotated by 90 degrees. Is this a bug?

**Comment by teymurov27** [comment]
Hi, did you solve it ?

**Comment by david-wb** [comment]
nope

**Comment by hyfan1116** [comment]
Hi @david-wb @teymurov27 to close the loop there is a bug on x/y coords being swapped when generating png / pgm. It has been updated.
